# Generated by Django 5.0.4 on 2024-05-12 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="length",
            field=models.CharField(
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="[0-9]{2}:[0-9]{2}:[0-9]{2}"
                    )
                ],
                verbose_name="Продолжительность фильма",
            ),
        ),
    ]
