# Generated by Django 5.0.4 on 2024-05-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_movie_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
